Traceback (most recent call last):
  File "tools/infer.py", line 222, in <module>
    prob = infer_main(args)
  File "tools/infer.py", line 180, in infer_main
    inference_engine = InferenceEngine(args)
  File "tools/infer.py", line 43, in __init__
    os.path.join(args.model_dir, "inference.pdiparams"))
  File "tools/infer.py", line 85, in load_predictor
    predictor = inference.create_predictor(config)
RuntimeError: (NotFound) Cannot open file ./log/PReNet/lite_train_lite_infer/norm_train_gpus_0,1/inference.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at /paddle/paddle/fluid/inference/api/analysis_predictor.cc:1116)

